name: Release to NPM
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
           node-version: 20
           registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Bundle Package
        run: npm run bundle
