name: "Shared setup for Node.js"
description: "Common steps to checkout code, setup Node.js, and install dependencies"
inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20"
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
